In [9]:
#python zip explain
l1 = [1,2,3,4]
l2 = [5,6,7,8]
list(zip(l1,l2))

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [3]:
#using python list
import time

size = 1_000_000_0
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
print(add[0:20])
end = time.time()

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
0.43147778511047363


In [6]:
#using numpy array
import numpy as np
import time

size = 1_000_000_0
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
print(add[0:20])
end = time.time()

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
0.022307634353637695


In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [15]:
arr = np.array([[1,2,3], [4,5,6]]) #size of the row in array should be same, otherwise it'll throw an error
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
type(arr)

numpy.ndarray

In [17]:
arr.shape

(2, 3)

In [18]:
#NumPy stores data in a contiguous memory block, making access faster than lists.
#NumPy arrays use significantly less memory compared to Python lists.


In [20]:

#Summary
#NumPy is faster than Python lists because it is optimized in C.
#It consumes less memory due to efficient storage.
#It provides vectorized operations, removing the need for slow loops.
#Essential for data science and machine learning workflows.