In [31]:
import numpy as np

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [33]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
flat = arr.flatten()

In [35]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
print(flat[5])

6


In [37]:
flat[:5] #first five elements

array([1, 2, 3, 4, 5])

In [38]:
flat[::2] #every second elements

array([ 1,  3,  5,  7,  9, 11])

In [39]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
flat[[1,4,5,7]] #this return the index element.

array([2, 5, 6, 8])

In [41]:
flat[flat>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [42]:
import random

In [53]:
#creating random 3 x 3 array 
arr1 = np.random.randint(1,100, size = (3, 3))

In [54]:
arr1

array([[24, 30, 73],
       [80, 31, 58],
       [26, 38, 92]])

In [55]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])

In [59]:
arr2[arr2%2==0]

array([2, 4, 6, 8])