In [10]:
#Summary:
#Loops are slow because Python's interpreter adds overhead, making iteration less efficient.
#Vectorization allows you to apply operations to entire arrays at once, 
#    greatly improving performance by utilizing NumPy’s optimized C backend.
#Broadcasting enables operations between arrays of different shapes by 
#    automatically stretching the smaller array to match the shape of the larger array, without creating additional copies.
#Real-world use: Broadcasting can be used in data science tasks, 
#    such as normalizing datasets, without sacrificing memory or performance.


In [11]:
import numpy as np

In [12]:
arr = np.array([1, 2, 3, 4, 5])

In [13]:
arr + 10  # Broadcasting: 10 is added to all elements

array([11, 12, 13, 14, 15])

In [14]:
#Here, the scalar 10 is "broadcast" across the entire array, and no extra memory is used.

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
 
result = arr1 + arr2  # Element-wise addition

In [16]:
result

array([11, 22, 33])

In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
 
result = arr1 + arr2  # Broadcasting arr2 across arr1

In [18]:
result

array([[2, 4, 6],
       [5, 7, 9]])

In [19]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
 
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
 
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
 
print(normalized_data)



[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
