In [1]:
import numpy as np

In [34]:
arr = np.array([1,33,45,67,88,99])

In [35]:
arr1 = np.array([12,33,44,66,77,88])

In [36]:
arr

array([ 1, 33, 45, 67, 88, 99])

In [37]:
np.mean(arr) #Compute the mean (average) of an array.

np.float64(55.5)

In [38]:
np.median(arr) #Compute the median of an array.

np.float64(56.0)

In [39]:
np.std(arr) #Compute the standard deviation of an array.

np.float64(33.33541660156657)

In [40]:
np.var(arr) #Compute the variance of an array

np.float64(1111.25)

In [41]:
np.min(arr) #Compute the minimum value of an array.

np.int64(1)

In [42]:
np.max(arr) #Compute the maximum value of an array.

np.int64(99)

In [43]:
np.sum(arr) #Compute the sum of all elements in an array

np.int64(333)

In [44]:
np.prod(arr) #Compute the product of all elements in an array.

np.int64(866800440)

In [45]:
np.percentile(arr, 56) #Compute the percentile of an array.

np.float64(62.60000000000001)

In [46]:
np.argmin(arr) #Return the index of the minimum value in an array.

np.int64(0)

In [47]:
np.argmax(arr) #Return the index of the maximum value in an array.

np.int64(5)

In [48]:
np.corrcoef(arr, arr1) #Compute the correlation coefficient matrix of two arrays.

array([[1.        , 0.99668538],
       [0.99668538, 1.        ]])

In [49]:
np.unique(arr) #Find the unique elements of an array.

array([ 1, 33, 45, 67, 88, 99])

In [50]:
np.diff(arr) #Compute the n-th differences of an array

array([32, 12, 22, 21, 11])

In [51]:
np.cumsum(arr) #Compute the cumulative sum of an array.

array([  1,  34,  79, 146, 234, 333])

In [52]:
np.log(arr) #Compute the natural logarithm of an array.

array([0.        , 3.49650756, 3.80666249, 4.20469262, 4.47733681,
       4.59511985])

In [53]:
np.exp(arr) #Compute the exponential of an array

array([2.71828183e+00, 2.14643580e+14, 3.49342711e+19, 1.25236317e+29,
       1.65163625e+38, 9.88903032e+42])