In [1]:
import numpy as np

In [3]:
#1. from an array [5,10,15,20,25,30], extract:
arr1 = np.array([5,10,15,20,25,30])

In [6]:
#Only even numbers
arr1[arr1%2==0]

array([10, 20, 30])

In [7]:
#Numbers greater than 15
arr1[arr1>15]

array([20, 25, 30])

In [8]:
#2. Access the second row of a 2D array.
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [9]:
arr2[1]

array([4, 5, 6])

In [17]:
#Extract the last column from a matrix.
arr2[:, -1]

array([ 3,  6,  9, 12])

In [20]:
#3. Replace all values greater than 50 with 50 in an array.
arr3 = np.array([5,10,15,20,75,60,76,89,90,56])

In [21]:
arr3[arr3>50] = 50

In [22]:
arr3

array([ 5, 10, 15, 20, 50, 50, 50, 50, 50, 50])

In [23]:
#4. Count how many values are greater than the mean of the array.
arr4 = np.array([5,10,15,20,25,30])

In [26]:
mean = arr4.mean()
mean

np.float64(17.5)

In [27]:
count = np.sum(arr4>mean)
count

np.int64(3)

In [28]:
#5. Find the index of the maximum value in an array.
arr5 = np.array([5,10,15,20,25,30])

In [30]:
np.argmax(arr5)

np.int64(5)

In [39]:
matrix = np.array([[1, 9, 10],
                   [4, 2, 6]])

np.argmax(matrix)       
np.unravel_index(np.argmax(matrix), matrix.shape)


(np.int64(0), np.int64(2))

In [41]:
#6. Reverse a NumPy array.
arr6 = np.array([5,10,15,20,25,30])

In [42]:
arr6[::-1]

array([30, 25, 20, 15, 10,  5])

In [43]:
#7. Replace all odd numbers with -1.
arr6[arr6%2!=0]=-1

In [44]:
arr6

array([-1, 10, -1, 20, -1, 30])

In [48]:
#8. Select elements at even indices only.
arr8 = np.array([5,10,15,20,25,30])
arr8[::2]

array([ 5, 15, 25])

In [52]:
#Check if a given array contains any NaN values.
arr = np.array([1, 2, np.nan, 4])

np.isnan(arr)

array([False, False,  True, False])

In [53]:
np.isnan(arr).sum()

np.int64(1)

In [55]:
np.where(np.isnan(arr))

(array([2]),)

In [57]:
matrix = np.array([[1, 2],
                   [np.nan, 4]])

np.isnan(matrix)

array([[False, False],
       [ True, False]])

In [58]:
np.where(np.isnan(matrix))

(array([1]), array([0]))