In [23]:
import numpy as np

In [24]:
#1. Create a NumPy array from a Python list [10, 20, 30, 40, 50].
arr1 = np.zeros(8)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
#2. Create a 2D array (3×3) filled with ones.
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#3. Generate an array of numbers from 5 to 50 with step 5.
arr3 = np.arange(5,50,5)
arr3

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
#4. Convert a list of strings ["1", "2", "3"] into integers using NumPy.
lst = ["1", "2", "3"]
arr4 = np.array(lst, dtype = 'int64')
arr4

array([1, 2, 3])

In [28]:
#5. Create an identity matrix of size 4×4.
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#6. Generate 10 random numbers between 0 and 1.
import random
arr6 = np.random.uniform(0,1,10)
arr6

array([0.14544016, 0.00974914, 0.18273308, 0.20456487, 0.61592508,
       0.46973946, 0.33946022, 0.84386355, 0.8899865 , 0.85230302])

In [30]:
#7. Change the shape of a 1D array of size 12 into (3,4).
arr1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr7 = arr1D.reshape(3,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
#8. Flatten a 2D NumPy array.
arr2D = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
flat = arr2D.flatten()

In [35]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])