In [1]:
#Create a NumPy array from a Python list [10, 20, 30, 40, 50].

Create a 1D array of zeros of length 8.

Create a 2D array (3×3) filled with ones.

Generate an array of numbers from 5 to 50 with step 5.


Convert a list of strings ["1", "2", "3"] into integers using NumPy.

Create an identity matrix of size 4×4.

Generate 10 random numbers between 0 and 1.

Change the shape of a 1D array of size 12 into (3,4).

Flatten a 2D NumPy array.

In [15]:
import numpy as np

In [16]:
#1. Create a NumPy array from a Python list [10, 20, 30, 40, 50].
arr1 = np.zeros(8)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#2. Create a 2D array (3×3) filled with ones.
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#3. Generate an array of numbers from 5 to 50 with step 5.
arr3 = np.arange(5,50,5)
arr3

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
#4. Convert a list of strings ["1", "2", "3"] into integers using NumPy.
lst = ["1", "2", "3"]
arr4 = np.array(lst, dtype = 'int64')
arr4

array([1, 2, 3])

In [21]:
#5. Create an identity matrix of size 4×4.
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#6. Generate 10 random numbers between 0 and 1.
import random
arr6 = np.random.uniform(0,1,10)
arr6

array([0.57579282, 0.55829096, 0.56797709, 0.59313485, 0.97119856,
       0.03046219, 0.99908345, 0.57993738, 0.17036345, 0.77886623])

In [34]:
#7. Change the shape of a 1D array of size 12 into (3,4).
arr1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
arr7 = arr1D.reshape(3,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
#8. Flatten a 2D NumPy array.
arr2D = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
flat = arr2D.flatten()

In [41]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])