In [13]:
#Unlike lists, all elements must have the same data type.
#NumPy arrays are strongly typed, meaning all elements share the same data type.
#Efficient memory usage by choosing the right data type.

In [14]:
import numpy as np

In [15]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [16]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
myarr.dtype

dtype('int64')

In [19]:
myarr.ndim #2 = 2 dimension

2

In [27]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
n = myarr.astype('float64')
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [29]:
n.dtype

dtype('float64')

In [30]:
myarr.shape

(4, 3)

In [36]:
#reshaped can only happen when the number of element should be same
#like 4x3 = element
#so has 3x4, 2x6, 6x2 
#but it can't be reshaped as 2x5 which has 10 element
reshaped = myarr.reshape((3,4))


In [37]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])