In [1]:
#Unlike lists, all elements must have the same data type.
#NumPy arrays are strongly typed, meaning all elements share the same data type.
#Efficient memory usage by choosing the right data type.

In [2]:
import numpy as np

In [3]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr.ndim #2 = 2 dimension

2

In [7]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
n = myarr.astype('float64')
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [9]:
n.dtype

dtype('float64')

In [10]:
myarr.shape

(4, 3)

In [11]:
#reshaped can only happen when the number of element should be same
#like 4x3 = element
#so has 3x4, 2x6, 6x2 
#but it can't be reshaped as 2x5 which has 10 element
reshaped = myarr.reshape((3,4))


In [12]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr1 = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
reshaped1 = arr1.reshape((3,3))

In [16]:
reshaped1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])