In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [8]:
np.sum(arr, axis = 0) #sum along  rows, axis = 0

array([12, 15, 18])

In [9]:
np.sum(arr, axis = 1) #sum along column, axis = 1

array([ 6, 15, 24])

In [10]:
#indexing

In [14]:
print(arr[0,1])

2


In [15]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [16]:
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [17]:
arr3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

In [19]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
arr3d[0,0,1] #depths, rows and column

np.int64(2)

In [22]:
arr3d[0,0,0:3]

array([1, 2, 3])

In [23]:
arr3d[0,0,0:3] = 0

In [24]:
arr3d

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])